"use client";

import React, { useState, useEffect } from "react";
import { masterProvisionTenant } from "@/lib/actions/salon-master-admin";

// Explicitly define the structural interface contract for the form state object
interface SalonFormState {
  ownerName: string;
  ownerEmail: string;
  passwordRaw: string;
  businessName: string;
  slug: string; // 🌟 Added explicit slug control tracking column
  tier: "trial" | "basic_single" | "growth_multi" | "enterprise_infinity";
  firstOutletName: string;
  firstOutletAddress: string;
  firstOutletPhone: string;
}

// 🔴 CRITICAL AUDIT: Mirror reserved system routing keys for client-side feedback acceleration
const RESERVED_SUBDOMAINS = [
  "www", "admin", "api", "glam", "pms", "pms-admin", "master-hub", 
  "login", "auth", "status", "cloud", "assets", "static", "mail", "system"
];

export default function MasterAdminHub() {
  const [adminSecret, setAdminSecret] = useState<string>("");
  const [isAuthorized, setIsAuthorized] = useState<boolean>(false);
  const [authError, setAuthError] = useState<string | null>(null);

  // Bind the interface schema strictly to the useState hook definition row
  const [form, setForm] = useState<SalonFormState>({
    ownerName: "",
    ownerEmail: "",
    passwordRaw: "",
    businessName: "",
    slug: "", // Initial empty state matching schema requirements
    tier: "trial", // Strictly enforced union type literal
    firstOutletName: "",
    firstOutletAddress: "",
    firstOutletPhone: "",
  });

  const [status, setStatus] = useState<{ success: boolean; msg: string } | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [slugFeedback, setSlugFeedback] = useState<{ isInvalid: boolean; warning: string | null }>({
    isInvalid: false,
    warning: null
  });

  // 🌟 Realtime Autogenerated Slug Watcher & Security Validation Rules Engine
  useEffect(() => {
    let generatedSlug = "";
    if (form.businessName.trim()) {
      generatedSlug = form.businessName
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, "") // Remove special characters
        .replace(/[\s_-]+/g, "-") // Convert spaces/underscores to single dashes
        .replace(/^-+|-+$/g, ""); // Trim edge fragments
    }

    // Evaluate structural boundary criteria rules
    let warning: string | null = null;
    let isInvalid = false;

    if (generatedSlug) {
      if (generatedSlug.length > 63) { // 🟠 HIGH: RFC 1035 spec boundary limits
        warning = "Subdomain key string length cannot exceed 63 characters.";
        isInvalid = true;
      } else if (RESERVED_SUBDOMAINS.includes(generatedSlug)) { // 🔴 CRITICAL: Core namespace reservation block
        warning = `"${generatedSlug}" is a reserved system route key template. Change name context.`;
        isInvalid = true;
      }
    }

    setSlugFeedback({ isInvalid, warning });
    setForm((prev) => ({ ...prev, slug: generatedSlug }));
  }, [form.businessName]);

  // Phase 1: Client Gatekeeper Interface Switcher
  const handleVerifyGate = async (e: React.FormEvent) => {
    e.preventDefault();
    setAuthError(null);

    if (!adminSecret.trim()) {
      setAuthError("Secret authorization token input cannot be empty.");
      return;
    }

    setIsAuthorized(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setStatus(null);

    // Defensive check to block formatting breaks prior to sending payload across server boundaries
    if (!form.slug.trim()) {
      setStatus({ success: false, msg: "Tenant Routing Slug identifier cannot be empty." });
      setLoading(false);
      return;
    }

    if (slugFeedback.isInvalid) {
      setStatus({ success: false, msg: slugFeedback.warning ?? "Please correct domain validation errors." });
      setLoading(false);
      return;
    }

    // Construct a strictly mapped, completely isolated payload structure
    const cleanPayload = {
      secretKey: adminSecret.trim(),
      ownerName: form.ownerName.trim(),
      ownerEmail: form.ownerEmail.trim(),
      passwordRaw: form.passwordRaw,
      businessName: form.businessName.trim(),
      slug: form.slug.trim(), // 🌟 Expelling the explicit required string slug parameter down to Drizzle Values
      tier: form.tier, // Aligns 100% with the required server action enum types
      firstOutletName: form.firstOutletName.trim(),
      firstOutletAddress: form.firstOutletAddress.trim(),
      firstOutletPhone: form.firstOutletPhone.trim(),
    };

    const res = await masterProvisionTenant(cleanPayload);
    
    setLoading(false);
    
    if (res.success) {
      setStatus({ success: true, msg: res.message ?? "Tenant workspace initialized successfully." });
      
      // Reset form fields cleanly on successful creation
      setForm({
        ownerName: "",
        ownerEmail: "",
        passwordRaw: "",
        businessName: "",
        slug: "",
        tier: "trial",
        firstOutletName: "",
        firstOutletAddress: "",
        firstOutletPhone: "",
      });
    } else {
      setStatus({ success: false, msg: res.error ?? "An unexpected provisioning execution error occurred." });
      
      // If the server returns a structural breach rejection, eject user context out immediately
      if (res.error?.includes("Authorization Breach") || res.error?.includes("Terminated Natively")) {
        setIsAuthorized(false);
        setAdminSecret(""); 
        setAuthError("Invalid Server Secret Token Provided. Access Revoked Natively.");
      }
    }
  };

  // 🔒 GATEKEEPER VIEW
  if (!isAuthorized) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center px-4 selection:bg-red-500 selection:text-white">
        <div className="w-full max-w-md bg-slate-900 border border-slate-800/60 p-8 rounded-2xl shadow-2xl text-center">
          <div className="text-3xl mb-3 select-none">🔒</div>
          <h1 className="text-lg font-black tracking-wider text-red-400 uppercase select-none">Master Admin Protection Boundary</h1>
          <p className="text-xs text-slate-400 mt-1 mb-6 select-none">Provide the server environment configuration secret key to unlock provisioning tables.</p>
          
          {authError && (
            <div className="mb-4 p-3 bg-red-950/40 border border-red-800/40 rounded-xl text-xs text-red-300 font-semibold max-w-full break-words">
              ⚠️ {authError}
            </div>
          )}
          
          <form onSubmit={handleVerifyGate} className="space-y-4">
            <input 
              type="password" 
              required 
              value={adminSecret} 
              onChange={e => setAdminSecret(e.target.value)} 
              placeholder="ENTER MASTER_ADMIN_SECRET" 
              className="w-full px-4 py-3 bg-slate-950 border border-slate-800 rounded-xl text-center text-sm tracking-widest text-orange-400 font-mono focus:border-orange-500/80 focus:ring-1 focus:ring-orange-500/20 outline-none transition" 
            />
            <button 
              type="submit" 
              className="w-full py-3 bg-red-950/30 hover:bg-red-900/40 border border-red-800/50 rounded-xl text-xs font-bold uppercase tracking-widest text-red-200 transition cursor-pointer select-none"
            >
              Initialize Authority Validation
            </button>
          </form>
        </div>
      </div>
    );
  }

  // 👑 MASTER VIEW
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8 flex flex-col items-center selection:bg-amber-500 selection:text-slate-950">
      <div className="w-full max-w-2xl bg-slate-900 border border-slate-800/80 rounded-2xl p-8 shadow-2xl">
        <div className="mb-6 border-b border-slate-800/60 pb-4 flex justify-between items-center select-none">
          <div>
            <h1 className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-500">
              👑 GLOBAL SUPER-ADMIN HUB
            </h1>
            <p className="text-xs text-slate-400 mt-1 uppercase tracking-wider font-semibold">
              SaaS Client & Tenant Account Provisioning Matrix
            </p>
          </div>
          <span className="text-[10px] bg-emerald-950 border border-emerald-800/60 px-3 py-1 text-emerald-400 rounded-full font-mono font-bold tracking-wider animate-pulse">
            SECURE STACK ACCESS
          </span>
        </div>

        {status && (
          <div className={`p-4 rounded-xl text-xs font-semibold mb-6 border ${
            status.success 
              ? "bg-emerald-950/40 border-emerald-800 text-emerald-300" 
              : "bg-red-950/40 border-red-800 text-red-300"
          }`}>
            {status.success ? "✓" : "⚠️"} {status.msg}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Owner / Tenant Name</label>
              <input type="text" required value={form.ownerName} onChange={e => setForm({...form, ownerName: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="Tenant Administrator" />
            </div>
            <div>
              <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Owner Core Email</label>
              <input type="email" required value={form.ownerEmail} onChange={e => setForm({...form, ownerEmail: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="partner@glamdomain.com" />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Default Access Password</label>
              <input type="password" required value={form.passwordRaw} onChange={e => setForm({...form, passwordRaw: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="••••••••" />
            </div>
            <div>
              <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Business / Brand Name</label>
              <input type="text" required value={form.businessName} onChange={e => setForm({...form, businessName: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="Ethereal Glam Studio" />
            </div>
          </div>

          {/* 🌟 NEW: INTERACTIVE SUBDOMAIN VISUAL REWRITE TRACKER FIELD WITH CLIENT VALIDATIONS */}
          <div>
            <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">
              Allocated Router Domain Node Identifier (Subdomain)
            </label>
            <div className="relative flex items-center">
              <input 
                type="text" 
                required 
                value={form.slug} 
                onChange={e => setForm({...form, slug: e.target.value.toLowerCase().replace(/[\s_]+/g, "-")})} 
                className={`w-full pl-4 pr-36 py-2.5 bg-slate-950 border rounded-xl text-sm font-mono focus:ring-1 transition ${
                  slugFeedback.isInvalid 
                    ? "border-red-500/80 text-red-400 focus:ring-red-500/20" 
                    : "border-slate-800 text-amber-400 focus:border-amber-500/80 focus:ring-amber-500/20"
                }`} 
                placeholder="prayagraj-studio" 
              />
              <span className="absolute right-3 text-xs font-semibold text-slate-500 font-mono pointer-events-none select-none">
                .etherealinn.com
              </span>
            </div>
            {slugFeedback.isInvalid ? (
              <p className="text-[10px] text-red-400 font-semibold mt-1.5 animate-pulse">
                ❌ {slugFeedback.warning}
              </p>
            ) : (
              <p className="text-[10px] text-slate-500 font-medium mt-1.5">
                Automated rewrite matching maps this context via edge proxy headers seamlessly into your shared views.
              </p>
            )}
          </div>

          <div>
            <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Software Rental Tier License</label>
            <select 
              value={form.tier} 
              onChange={e => setForm({...form, tier: e.target.value as SalonFormState["tier"]})} 
              className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm text-slate-300 focus:border-amber-500/80 outline-none transition bg-slate-900"
            >
              <option value="trial">Free Trial Workspace (Max 1 Outlet)</option>
              <option value="basic_single">Basic Rental Tier (Max 1 Outlet)</option>
              <option value="growth_multi">Growth Multi-Outlet Plan (Max 5 Outlets)</option>
              <option value="enterprise_infinity">Enterprise Infinity Account (Unlimited Outlets)</option>
            </select>
          </div>

          <div className="pt-4 border-t border-slate-800/60 space-y-4">
            <h3 className="text-xs uppercase font-bold text-slate-400 tracking-widest select-none">Base Physical Outlet Configuration</h3>
            <div>
              <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">First Location Branch Name</label>
              <input type="text" required value={form.firstOutletName} onChange={e => setForm({...form, firstOutletName: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="Ethereal Glam - GK2 Main Branch" />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Branch Full Address</label>
                <input type="text" required value={form.firstOutletAddress} onChange={e => setForm({...form, firstOutletAddress: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="Greater Kailash Part 2, New Delhi" />
              </div>
              <div>
                <label className="block text-[11px] font-bold uppercase text-slate-400 mb-2 tracking-wider select-none">Branch Contact Phone</label>
                <input type="text" required value={form.firstOutletPhone} onChange={e => setForm({...form, firstOutletPhone: e.target.value})} className="w-full px-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm focus:border-amber-500/80 outline-none transition text-slate-200" placeholder="+91 98765 43210" />
              </div>
            </div>
          </div>

          <button 
            type="submit" 
            disabled={loading || slugFeedback.isInvalid} 
            className="w-full py-3 bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 text-slate-950 font-black text-sm tracking-wider uppercase rounded-xl transition shadow-xl disabled:opacity-40 cursor-pointer flex items-center justify-center gap-2 select-none"
          >
            {loading ? (
              <>
                <svg className="animate-spin h-4 w-4 text-slate-950" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
                Deploying Multi-Tenant Schema Rows...
              </>
            ) : (
              "Launch Isolated Tenant Workspace"
            )}
          </button>
        </form>
      </div>
    </div>
  );
}